### ISSUE TITLE
Feature quest: allow switch MIRPS source

### ISSUE THREAD

**Issue by Seele-Vollerei32** [poly000/waylyrics#43]
As the title, if more than one MIRPS source exists, we need a way to switch to the proper one.

**Comment by poly000** [comment]
the current mechanism is, get likely active one only if the old player shutdowns. tp avoid rapid switch between players
anyway, allow to select mpris source manually is still useful. so I will leave this open

**Comment by poly000** [comment]
@poly000 this issue will hangs until #19 is done

**Comment by poly000** [comment]
@poly000 for a temporary solution, we shall register a SIGUSR1 handler and disconnect from current player once received such signal.
should check signal

**Comment by poly000** [comment]
After adding CSD menu, waylyrics allows to switch to specified player
